# Generated by Django 2.2 on 2020-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='general_access',
            field=models.CharField(choices=[('general', 'Общий'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='general', max_length=50, verbose_name='Общий доступ'),
        ),
    ]
